<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Subpreguntas;

class SubpreguntaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $preguntasPorSubpreguntas = [
            '2' => [
                '1' => ['texto' => 'Administrativo',
                        'puntaje' => '2'],
                '2' => ['texto' => 'Desarrollo',
                'puntaje' => '2'],
                '3' => ['texto' => 'Producción',
                'puntaje' => '2'],
                '4' => ['texto' => 'Innovacion y/o desarrollo',
                        'puntaje' => '2'],
                '5' => ['texto' => 'Comercialización',
                        'puntaje' => '2'],
                '6' => ['texto' => 'Otro, cuál / cuántos?',
                'puntaje' => '0'],
            ],
            '12'=>[
                '7'=>['texto' => 'Meta 1',
                    'puntaje' => '0'],
                '8'=>['texto' => 'Meta 2',
                    'puntaje' => '0'],
                '9'=>['texto' => 'Meta 3',
                    'puntaje' => '0'],
                '10'=>['texto' => 'Meta 4',
                    'puntaje' => '0'],
            ],
            '17'=>[
                '11'=>['texto' => 'Gastos fijos',
                    'puntaje' => '2'],
                '12'=>['texto' => 'Gastos variables',
                    'puntaje' => '2'],
                '13'=>['texto' => 'Gastos operacionales',
                    'puntaje' => '2'],
                '14'=>['texto' => 'Gastos no operacionales',
                    'puntaje' => '2'],
                '15'=>['texto' => 'Costos fijos',
                    'puntaje' => '2'],
                '16'=>['texto' => 'Costos variables',
                    'puntaje' => '2'],
                '17'=>['texto' => 'Costos directos',
                    'puntaje' => '2'],
                '18'=>['texto' => 'Costos indirectos',
                'puntaje' => '2'],
            ],
            '19'=>[
                '19'=>['texto' => 'Balance general',
                    'puntaje' => '2'],
                '20'=>['texto' => 'Estado de flujo',
                    'puntaje' => '2'],
                '21'=>['texto' => 'Registro de compras',
                    'puntaje' => '2'],
                '22'=>['texto' => 'Registro de ventas',
                    'puntaje' => '2'],
                '23'=>['texto' => 'Otro ¿Cual?',
                    'puntaje' => '0'],
              
            ],
            '21'=>[
                '24'=>['texto' => 'Ingreso',
                    'puntaje' => '2'],
                '25'=>['texto' => 'Egreso',
                    'puntaje' => '2'],
                '26'=>['texto' => 'Deudas',
                    'puntaje' => '2'],
                '27'=>['texto' => 'Otro ¿Cual?',
                    'puntaje' => '0'],
            ],
            '23'=>[
                '28'=>['texto' => 'Costos',
                    'puntaje' => '2'],
                '29'=>['texto' => 'Demanda',
                    'puntaje' => '2'],
                '30'=>['texto' => 'Competencia',
                    'puntaje' => '2'],
                '31'=>['texto' => 'Otro ¿Cual?',
                    'puntaje' => '0'],
            ],
            '24'=>[
                '32'=>['texto' => 'Prestamo formal',
                    'puntaje' => '2'],
                '33'=>['texto' => 'Prestamo informal',
                    'puntaje' => '2'],
                '34'=>['texto' => 'Disminuyendo gastos',
                    'puntaje' => '2'],
                '35'=>['texto' => 'Ahorros/propios',
                    'puntaje' => '2'],
                '36'=>['texto' => 'Otro ¿Cual?',
                    'puntaje' => '0'],
            ],
            '26'=>[
                '37'=>['texto' => 'Ingreso supperior al egreso',
                    'puntaje' => '2'],
                '38'=>['texto' => 'Ingreso superior al egreso',
                    'puntaje' => '2'],
                '39'=>['texto' => 'ingreso inferior al egreso',
                    'puntaje' => '2'],
                '40'=>['texto' => 'No sabe',
                    'puntaje' => '1'],
            ],
            '27'=>[
                '41'=>['texto' => 'Punto de venta',
                    'puntaje' => '2'],
                '42'=>['texto' => 'Telemarketing',
                    'puntaje' => '2'],
                '43'=>['texto' => 'Marketplace',
                    'puntaje' => '2'],
                '44'=>['texto' => 'Ecommerce',
                    'puntaje' => '2'],
                '45'=>['texto' => 'Otro ¿Cual?',
                    'puntaje' => '0'],
            ],
            '29'=>[
                '46'=>['texto' => 'Iva',
                    'puntaje' => '2'],
                '47'=>['texto' => 'Ica',
                    'puntaje' => '2'],
                '48'=>['texto' => 'Retefuente',
                    'puntaje' => '2'],
                '49'=>['texto' => 'Impuesto a la renta',
                    'puntaje' => '2'],
            ],
            '42'=>[
                '50'=>['texto' => '¿La propuesta cuenta con una identificación básica de información científica susceptible de ser aplicada?',
                    'puntaje' => '2'],
                '51'=>['texto' => '¿Tiene al menos una imagen general de lo que debe hacer su producto y/o servicio?',
                    'puntaje' => '2'],
                '52'=>['texto' => '¿Tiene claridad en las necesidades para el desarrollo de su producto y/o servicio?',
                    'puntaje' => '2'],
                '53'=>['texto' => '¿Se cuenta con un aparente diseño que dé solución a la oportunidad detectada?',
                    'puntaje' => '2'],
                '54'=>['texto' => '¿Los elementos básicos del producto y/o servicio se encuentran identificados?',
                    'puntaje' => '2'],
                '55'=>['texto' => '¿Se cuenta con experiencia en el desarrollo de producto y/o servicios similares?',
                    'puntaje' => '2'],
                '56'=>['texto' => '¿Tiene algún cliente interesado ya en dicho producto y/o servicio?',
                    'puntaje' => '2'],
                '57'=>['texto' => '¿Se tiene claro los requerimientos legales para la puesta en marcha del producto y o servicio propuesto?',
                    'puntaje' => '2'],
                '58'=>['texto' => '¿El producto y/o servicio resuelve la necesidad del mercado de manera sostenible?',
                    'puntaje' => '2'],
                '59'=>['texto' => '¿Se cuenta con un modelo/prototipo de simulación del producto y/o servicio?',
                    'puntaje' => '2'],
                '60'=>['texto' => '¿Se tienen estrategias de mitigación de riesgos identificados?',
                    'puntaje' => '2'],
                '61'=>['texto' => '¿Los diseños del producto y/o servicio ya se encuentra validados en entorno controlado?',
                    'puntaje' => '2'],
                '62'=>['texto' => '¿se conoce lo que se necesita para implementar producto y o servicio?',
                    'puntaje' => '2'],
                '63'=>['texto' => '¿El producto y/o servicio fue validado por un laboratorio y está validación es favorable adecuada?',
                    'puntaje' => '2'],
                '64'=>['texto' => '¿Los costos de la propuestas ya se encuentran analizados?',
                    'puntaje' => '2'],
                '65'=>['texto' => '¿Tiene definidos los proveedores de insumos y materiales para la ejecución del producto y/o servicio?',
                    'puntaje' => '2'],
                '66'=>['texto' => '¿Tiene definido criterios para la selección de proveedores?',
                    'puntaje' => '2'],
                '67'=>['texto' => '¿El producto esta validado a nivel de detalle?',
                    'puntaje' => '2'],
                '68'=>['texto' => '¿Han sido identificados los efectos adversos del producto y/o servicio?',
                    'puntaje' => '2'],
                '69'=>['texto' => '¿El producto y/o servicio ha sido validad en un entorno real?',
                    'puntaje' => '2'],
                '70'=>['texto' => '¿Producto y/o servicio ya esta lista para la producción?',
                    'puntaje' => '2'],
                '71'=>['texto' => '¿El producto y/o servicio cuenta con documentación de usuario, mantenimiento y de servicio especificadas y controladas?',
                    'puntaje' => '2'],
                '72'=>['texto' => '¿El producto y/o servicio esta validado, comprobado y acreditado completamente?',
                    'puntaje' => '2'],
                '73'=>['texto' => '¿El producto y/o servicio cuenta con una producción estable?',
                    'puntaje' => '2'],
                '74'=>['texto' => '¿Se tiene la capacidad para desarrollar el producto y/o servicio?',
                    'puntaje' => '2'],
                '75'=>['texto' => '¿Implementa planes de producción?',
                    'puntaje' => '2'],
                '76'=>['texto' => '¿Implementa planes de compra?',
                    'puntaje' => '2'],
                '77'=>['texto' => '¿El producto y/o servicio se encuentra implementado y funcionando?',
                    'puntaje' => '2'],
                '78'=>['texto' => '¿Tienen parámetros de calidad definidos para su producto y/o servicio?',
                    'puntaje' => '2'],
                '79'=>['texto' => '¿El producto y/o servicio cuenta con patente, propiedad intelectual y/o industrial registrada?',
                    'puntaje' => '2'],
                '80'=>['texto' => '¿El producto y/o servicio cuenta con certificados de calidad, ambientales, otros?',
                    'puntaje' => '2'],
            ],


            '45'=>[
                '81'=>['texto' => 'Apoyo tecnico',
                    'puntaje' => '2'],
                '82'=>['texto' => 'Capacitación',
                    'puntaje' => '2'],
                '83'=>['texto' => 'Financiamiento',
                    'puntaje' => '2'],
                '84'=>['texto' => 'Redes/alianza',
                    'puntaje' => '2'],
                '85'=>['texto' => 'Mejora de la calidad p/s',
                    'puntaje' => '2'],
                '86'=>['texto' => 'Infraestructura',
                    'puntaje' => '2'],
                '87'=>['texto' => 'Otro ¿Cual?',
                    'puntaje' => '0'],
            ],
            '47'=>[
                '88'=>['texto' => 'Apoyo tecnico',
                    'puntaje' => '2'],
                '89'=>['texto' => 'Capacitación',
                    'puntaje' => '2'],
                '90'=>['texto' => 'Financiamiento',
                    'puntaje' => '2'],
                '91'=>['texto' => 'Redes/alianza',
                    'puntaje' => '2'],
                '92'=>['texto' => 'Infraestructura',
                    'puntaje' => '2'],
                '93'=>['texto' => 'Aumento de clientes',
                    'puntaje' => '2'],
                '94'=>['texto' => 'Bajar costos y/o gastos',
                    'puntaje' => '2'],
                '95'=>['texto' => 'Mejorar ventas',
                    'puntaje' => '2'],
                '96'=>['texto' => 'Otro ¿Cual?',
                    'puntaje' => '0'],

            ]
        ];

        foreach($preguntasPorSubpreguntas as $idPregunta =>$preguntas ){
            foreach($preguntas as $nombrePregunta =>$contenido){
                Subpreguntas::create([
                    'texto' =>$contenido['texto'],
                    'puntaje' =>$contenido['puntaje'],
                    'id_pregunta' => $idPregunta
                ]);
            }
        }
    }
}
