version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:ngCRKpJCmEFJI7WHdV4+BY2zWjdBGNaJ5/aiZW3oUaM=
      - DB_CONNECTION=mysql
      - DB_HOST=roundhouse.proxy.rlwy.net
      - DB_PORT=12256
      - DB_DATABASE=seedlab
      - DB_USERNAME=root
      - DB_PASSWORD=eqiWKmwMxjBsIahcQdXdSDRxYatuqovO
